### PR TITLE
Aug 26 - Chapter 1 and the start of Chapter 2

### PR DESCRIPTION
**Pull request by Kumaxkuma**
- Use `python3 --version` to find version

- `>>>` is the interpreter which is where you can test things out before you write code to execute anything. Similar to a sandbox.

- To enter` >>>` use `python`
- When you close the interpreter it destroys everything you made in it

- `Control C` to start a new line if you accidentally put a command but don’t want to send it.

- `Touch` `file name` to create a file 

- `print(message)` to print message

Homework - Go through and read chapter 2 and do all chapter 2 try it yourself in pythoncrashcourse

`*1` means you changed a file and `?1` signifies an untracked file

### CODE REVIEW

**Comment by Julzerator** [comment]
Good stuff! Exciting to learn all of this!

**Comment by rayb33** [comment]
You're doing great <3

**Review by Julzerator — APPROVED** [review]
:shipit:

**Comment by Kumaxkuma** [comment]
Continued notes: 

After merging into `main` always go to your local terminal and `git checkout main` and do a `git pull`

After `git pull` if you see `fatal: Unable to read current working directory: No such file or directory` be sure to `cd` into the base directory and try it again

**Pull request merged**
